[2024-02-26 15:34:03] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (2) nodes unable to establish P2P communication due to exceptions
[2024-02-26 15:34:08] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (2) nodes unable to establish P2P communication due to exceptions
[2024-02-26 15:34:13] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (2) nodes unable to establish P2P communication due to exceptions
[2024-02-26 15:34:18] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (2) nodes unable to establish P2P communication due to exceptions
[2024-02-26 15:34:18] [warning] server.go:631 p3Chain/p2p/server.(*Server).setupConn dyn dial conn 9c932476cf018f45 127.0.0.1:20132 failed checkpoint posthandshake: Connected to self
[2024-02-26 15:34:18] [warning] server.go:631 p3Chain/p2p/server.(*Server).setupConn inbound conn 9c932476cf018f45 127.0.0.1:63124 failed checkpoint posthandshake: Connected to self
[2024-02-26 15:34:23] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (2) nodes unable to establish P2P communication due to exceptions
[2024-02-26 15:34:28] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (2) nodes unable to establish P2P communication due to exceptions
[2024-02-26 15:34:33] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (2) nodes unable to establish P2P communication due to exceptions
[2024-02-26 15:34:38] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (2) nodes unable to establish P2P communication due to exceptions
[2024-02-26 15:34:43] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (2) nodes unable to establish P2P communication due to exceptions
[2024-02-26 15:34:48] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (2) nodes unable to establish P2P communication due to exceptions
[2024-02-26 15:34:50] [warning] server.go:631 p3Chain/p2p/server.(*Server).setupConn inbound conn 9c932476cf018f45 127.0.0.1:63239 failed checkpoint posthandshake: Connected to self
[2024-02-26 15:34:50] [warning] server.go:631 p3Chain/p2p/server.(*Server).setupConn static dial conn 9c932476cf018f45 127.0.0.1:20132 failed checkpoint posthandshake: Connected to self
[2024-02-26 15:34:53] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (2) nodes unable to establish P2P communication due to exceptions
[2024-02-26 15:34:58] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (2) nodes unable to establish P2P communication due to exceptions
